name = "FSM"
uuid = "5f4fc399-9581-4006-a2d5-a6e0278e1921"
authors = ["jmg <jmg@nve.no> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
